//
// Generated file, do not edit! Created by nedtool 5.0 from src/Send.msg.
//

#ifndef __SEND_M_H
#define __SEND_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/Send.msg:3</tt> by nedtool.
 * <pre>
 * message Send
 * {
 *     string data;
 * }
 * </pre>
 */
class Send : public ::omnetpp::cMessage
{
  protected:
    ::omnetpp::opp_string data;

  private:
    void copy(const Send& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Send&);

  public:
    Send(const char *name=nullptr, int kind=0);
    Send(const Send& other);
    virtual ~Send();
    Send& operator=(const Send& other);
    virtual Send *dup() const {return new Send(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getData() const;
    virtual void setData(const char * data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Send& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Send& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SEND_M_H

